import = ["~/.config/alacritty/dracula.toml"]

[env]
	TERM = "xterm-256color"

[window]
	opacity = 0.95
	padding.x = 16
	padding.y = 16
	decorations = "Buttonless"
	position = { x = 492, y = 40 }
	dimensions = { columns = 112, lines = 51 }

[font]
	normal.family = "JetbrainsMono NF"
	size = 10

