general.import = ["~/.config/alacritty/dracula.toml"]

[env]
	TERM = "xterm-256color"

[window]
	padding.x = 16
	padding.y = 16
	opacity = 0.98
	decorations = "Buttonless"
	position = { x = 492, y = 40 }
	dimensions = { columns = 130, lines = 58 }

[font]
	normal.family = "JetbrainsMono NF"
	size = 14

